// Code generated by scripts/sync-sdk-config.mjs — DO NOT EDIT.
// Source of truth: packages/sdk/config.json
// Regenerate: npm run sync:sdk-config (from monorepo root)
package whyops

import "time"

const SDKVersion = "0.1.1"

// Default service URLs — used when proxyBaseURL / analyseBaseURL are not set in Config.
const (
	DefaultProxyURL   = "https://proxy.whyops.com"
	DefaultAnalyseURL = "https://a.whyops.com/api"
)

// HTTP settings
const HTTPTimeoutMs = 15000

// API endpoint paths appended to base URLs.
const (
	EndpointAgentInitPrimary  = "/entities/init"
	EndpointAgentInitFallback = "/v1/agents/init"
	EndpointEventsIngest      = "/events/ingest"
)

// HTTP header names.
const (
	HeaderAgentName      = "X-Agent-Name"
	HeaderAnthropicKey   = "x-api-key"
	HeaderContentType    = "Content-Type"
	HeaderContentJSON    = "application/json"
	LogPrefix            = "[whyops]"
)

var retryDelays = []time.Duration{200 * time.Millisecond, 400 * time.Millisecond, 800 * time.Millisecond}
var retryableStatuses = map[int]bool{
	429: true,
	500: true,
	502: true,
	503: true,
	504: true,
}

// EventType string enum — all supported values.
const (
	EventTypeUserMessage EventType = "user_message"
	EventTypeLLMResponse EventType = "llm_response"
	EventTypeLLMThinking EventType = "llm_thinking"
	EventTypeEmbeddingRequest EventType = "embedding_request"
	EventTypeEmbeddingResponse EventType = "embedding_response"
	EventTypeToolCall EventType = "tool_call"
	EventTypeToolCallRequest EventType = "tool_call_request"
	EventTypeToolCallResponse EventType = "tool_call_response"
	EventTypeToolResult EventType = "tool_result"
	EventTypeError EventType = "error"
)
