"""
Shared SDK config accessors.
Source of truth: packages/sdk/config.json
Generated constants: whyops/_config_gen.py
"""

from ._config_gen import (
    DEFAULT_ANALYSE_URL,
    DEFAULT_PROXY_URL,
    ENDPOINT_AGENT_INIT_FALLBACK,
    ENDPOINT_AGENT_INIT_PRIMARY,
    ENDPOINT_EVENTS_INGEST,
    EVENT_TYPES,
    EventType,
    HEADER_AGENT_NAME,
    HEADER_ANTHROPIC_KEY,
    HEADER_CONTENT_TYPE_NAME,
    HEADER_CONTENT_TYPE_VALUE,
    HTTP_TIMEOUT_S,
    LOG_PREFIX,
    REQUIRED_METADATA_BY_EVENT,
    RETRY_DELAYS_S,
    RETRYABLE_STATUS_CODES,
    SDK_VERSION,
)

__all__ = [
    "DEFAULT_ANALYSE_URL",
    "DEFAULT_PROXY_URL",
    "ENDPOINT_AGENT_INIT_FALLBACK",
    "ENDPOINT_AGENT_INIT_PRIMARY",
    "ENDPOINT_EVENTS_INGEST",
    "EVENT_TYPES",
    "EventType",
    "HEADER_AGENT_NAME",
    "HEADER_ANTHROPIC_KEY",
    "HEADER_CONTENT_TYPE_NAME",
    "HEADER_CONTENT_TYPE_VALUE",
    "HTTP_TIMEOUT_S",
    "LOG_PREFIX",
    "REQUIRED_METADATA_BY_EVENT",
    "RETRY_DELAYS_S",
    "RETRYABLE_STATUS_CODES",
    "SDK_VERSION",
]
