# Code generated by scripts/sync-sdk-config.mjs — DO NOT EDIT.
# Source of truth: packages/sdk/config.json
# Regenerate: npm run sync:sdk-config (from monorepo root)

from typing import Literal

SDK_VERSION = "0.1.0"

DEFAULT_PROXY_URL = "https://proxy.whyops.com"
DEFAULT_ANALYSE_URL = "https://a.whyops.com/api"

HTTP_TIMEOUT_S = 15
RETRY_DELAYS_S = [0.2,0.4,0.8]
RETRYABLE_STATUS_CODES = frozenset([429,500,502,503,504])

ENDPOINT_AGENT_INIT_PRIMARY = "/entities/init"
ENDPOINT_AGENT_INIT_FALLBACK = "/v1/agents/init"
ENDPOINT_EVENTS_INGEST = "/events/ingest"

HEADER_AGENT_NAME = "X-Agent-Name"
HEADER_ANTHROPIC_KEY = "x-api-key"
HEADER_CONTENT_TYPE_NAME = "Content-Type"
HEADER_CONTENT_TYPE_VALUE = "application/json"

LOG_PREFIX = "[whyops]"

EventType = Literal[
    "user_message",
    "llm_response",
    "llm_thinking",
    "embedding_request",
    "embedding_response",
    "tool_call",
    "tool_call_request",
    "tool_call_response",
    "tool_result",
    "error",
]

EVENT_TYPES: tuple[EventType, ...] = (
    "user_message",
    "llm_response",
    "llm_thinking",
    "embedding_request",
    "embedding_response",
    "tool_call",
    "tool_call_request",
    "tool_call_response",
    "tool_result",
    "error",
)

REQUIRED_METADATA_BY_EVENT: dict[str, list[str]] = {
    "llm_response": ["model","provider"],
    "embedding_response": ["model","provider"],
    "tool_call_request": ["tool"],
    "tool_call_response": ["tool"],
}
