// Code generated by scripts/sync-sdk-config.mjs — DO NOT EDIT.
// Source of truth: packages/sdk/config.json
// Regenerate: npm run sync:sdk-config (from monorepo root)

export const SDK_VERSION = "0.1.0" as const;

export const DEFAULT_PROXY_URL = "https://proxy.whyops.com" as const;
export const DEFAULT_ANALYSE_URL = "https://a.whyops.com/api" as const;

export const HTTP_TIMEOUT_MS = 15000 as const;
export const RETRY_DELAYS_MS = [200,400,800] as const;
export const RETRYABLE_STATUS_CODES = [429,500,502,503,504] as const;

export const ENDPOINTS = {
  agentInitPrimary: "/entities/init",
  agentInitFallback: "/v1/agents/init",
  eventsIngest: "/events/ingest",
} as const;

export const HEADERS = {
  agentName: "X-Agent-Name",
  apiKeyAnthropic: "x-api-key",
  contentTypeName: "Content-Type",
  contentTypeValue: "application/json",
} as const;

export const LOG_PREFIX = "[whyops]" as const;

export const EVENT_TYPES = [
  'user_message',
  'llm_response',
  'llm_thinking',
  'embedding_request',
  'embedding_response',
  'tool_call',
  'tool_call_request',
  'tool_call_response',
  'tool_result',
  'error',
] as const;

export const REQUIRED_METADATA_BY_EVENT = {
  'llm_response': ["model","provider"] as const,
  'embedding_response': ["model","provider"] as const,
  'tool_call_request': ["tool"] as const,
  'tool_call_response': ["tool"] as const,
} as const;
